import unittest
from pathlib import Path


class FrontendShortpickStaticTests(unittest.TestCase):
    def test_shortpick_lab_is_independent_research_surface(self) -> None:
        frontend_root = Path(__file__).resolve().parents[1] / "frontend" / "src"
        app_source = (frontend_root / "App.tsx").read_text(encoding="utf-8")
        component_source = (frontend_root / "components" / "ShortpickLabView.tsx").read_text(encoding="utf-8")
        api_source = (frontend_root / "api" / "shortpick.ts").read_text(encoding="utf-8")

        self.assertIn('label: "试验田"', app_source)
        self.assertIn("<ShortpickLabView canTrigger={isRootUser}", app_source)
        self.assertIn("独立研究课题，不进入主推荐评分", component_source)
        self.assertIn("冻结纸面策略进入正式跟踪", component_source)
        self.assertIn("LLM 自由选股保留为对照组", component_source)
        self.assertIn("LLM纸面对照标的", component_source)
        self.assertIn("每日固定规则选1只", component_source)
        self.assertIn("市场因子对照规则", component_source)
        self.assertIn("同池随机基线", component_source)
        self.assertIn("前三名等权组合", component_source)
        self.assertIn("10/200日金叉过滤", component_source)
        self.assertIn("低换手上升趋势", component_source)
        self.assertIn("等权市场基准", component_source)
        self.assertIn("中证500", component_source)
        self.assertIn("中证1000", component_source)
        self.assertIn("指数序列未纳入本次主板样本库，不展示为0。", component_source)
        self.assertIn("每日1万元在前三名等权", component_source)
        self.assertIn("纸面跟踪记录（正式策略与对照组）", component_source)
        self.assertIn("后验验证完成前仅作为探索结果展示", component_source)
        self.assertIn("sourceCredibilityLabel", component_source)
        self.assertIn("sourceCredibilityColor", component_source)
        self.assertIn("credibility_status", component_source)
        self.assertIn("校验：", component_source)
        self.assertIn("主基准：", component_source)
        self.assertIn("沪深300", component_source)
        self.assertIn("超额收益", component_source)
        self.assertIn("pending_benchmark_data", component_source)
        self.assertIn("待基准", component_source)
        self.assertIn("前向K线", component_source)
        self.assertIn("重跑接口返回 404", component_source)
        self.assertIn("shortpick-feedback-summary", component_source)
        self.assertIn("shortpick-feedback-table", component_source)
        self.assertIn("shortpick-benchmark-select", component_source)
        self.assertIn("shortpick-validation-card", component_source)
        self.assertIn('label: "历史回放"', component_source)
        self.assertIn("const visibleWorkspaceTab = latestRun || activeWorkspaceTab !== \"today\"", component_source)
        self.assertIn("activeKey={visibleWorkspaceTab}", component_source)
        self.assertIn("loadMarketStudy", component_source)
        self.assertIn("历史回放主体不依赖这项重计算", component_source)
        self.assertIn("候选明细加载中", component_source)
        self.assertIn("来源清单加载中", component_source)
        self.assertIn("全局统计加载中", component_source)
        self.assertIn("严格来源", component_source)
        self.assertIn("可交易验证", component_source)
        self.assertIn("选股模式双口径对照", component_source)
        self.assertIn("逐只候选统计，用来观察选股池平均质量", component_source)
        self.assertIn("长样本5万元滚动资金曲线超额", component_source)
        self.assertIn("短窗口候选统计", component_source)
        self.assertIn("组合资金曲线", component_source)
        self.assertIn('activeWorkspaceTab === "replay"', component_source)
        self.assertIn("void loadReplay(undefined, { includeMarketStudy: true })", component_source)
        self.assertIn("历史分析结论", component_source)
        self.assertIn("可执行性漏斗", component_source)
        self.assertIn("入场假设矩阵", component_source)
        self.assertIn("14点同日口径只按日线代理展示", component_source)
        self.assertIn("稳定性、置信与归因", component_source)
        self.assertIn("市场阶段", component_source)
        self.assertIn("行业/题材稳定性", component_source)
        self.assertIn("行业归因口径", component_source)
        self.assertIn("去最佳行业后", component_source)
        self.assertIn("下沿未过晋级线", component_source)
        self.assertIn("前向对齐", component_source)
        self.assertIn("页面不会临时推导研究结论", component_source)
        self.assertIn("shortpick-replay-decision-grid", component_source)
        self.assertIn("策略收口接口当前没有可展示数据", component_source)
        self.assertIn("暂无LLM对照批次；可先查看纸面跟踪或历史回放。", component_source)
        self.assertIn('label: "纸面跟踪"', component_source)
        self.assertIn("PaperTrackingTab", component_source)
        self.assertIn("getShortpickPaperTracking", api_source)
        self.assertIn("/shortpick-lab/paper-tracking", api_source)
        self.assertIn("历史回放核心读数", component_source)
        self.assertIn("无上下文直接查询能否短投选股", component_source)
        self.assertIn("1 / 3 / 5 / 10 / 20 日", component_source)
        self.assertIn("模型与对照组比较", component_source)
        self.assertIn("封闭数据包与来源清单", component_source)
        self.assertIn("泄漏审计", component_source)
        self.assertIn("random_same_market_cap_bucket", component_source)
        self.assertIn("momentum_volume_baseline", component_source)
        self.assertIn("去最佳单票", component_source)
        self.assertIn("getShortpickReplayRuns", api_source)
        self.assertIn("/shortpick-lab/replay-runs", api_source)
        self.assertNotIn("<Segmented", component_source)
        self.assertIn('align: "center"', component_source)
        self.assertIn("/shortpick-lab/runs", api_source)
        self.assertIn("/shortpick-lab/candidates", api_source)
        self.assertNotIn("addWatchlist", component_source)
        self.assertNotIn("getStockDashboard", component_source)

    def test_local_preview_does_not_fallback_to_vite_origin_for_api(self) -> None:
        frontend_root = Path(__file__).resolve().parents[1] / "frontend" / "src"
        core_source = (frontend_root / "api" / "core.ts").read_text(encoding="utf-8")

        self.assertIn("function isLocalPreviewOrigin()", core_source)
        self.assertIn("window.location.port !== \"8000\"", core_source)
        self.assertIn("isLocalPreviewOrigin() ? [] : [inferOriginBase()]", core_source)
        self.assertIn("!inferLocalBackendBase() && !basesToUse.includes(\"\")", core_source)


if __name__ == "__main__":
    unittest.main()
