import unittest
from pathlib import Path


class FrontendShortpickStaticTests(unittest.TestCase):
    def test_shortpick_lab_is_independent_research_surface(self) -> None:
        frontend_root = Path(__file__).resolve().parents[1] / "frontend" / "src"
        app_source = (frontend_root / "App.tsx").read_text(encoding="utf-8")
        component_paths = [
            frontend_root / "components" / "ShortpickLabView.tsx",
            frontend_root / "components" / "shortpickLabLabels.ts",
            frontend_root / "components" / "shortpickLabPaperTracking.ts",
            frontend_root / "components" / "shortpickLabReplayMetrics.ts",
            frontend_root / "components" / "shortpickLabToday.tsx",
        ]
        component_source = "\n".join(path.read_text(encoding="utf-8") for path in component_paths)
        api_source = (frontend_root / "api" / "shortpick.ts").read_text(encoding="utf-8")

        self.assertIn('label: "试验田"', app_source)
        self.assertIn("<ShortpickLabView canTrigger={isRootUser}", app_source)
        self.assertIn("独立研究课题，不进入主推荐评分", component_source)
        self.assertIn("冻结纸面策略进入正式跟踪", component_source)
        self.assertIn("LLM 自由选股保留为对照组", component_source)
        self.assertIn("LLM纸面对照标的", component_source)
        self.assertIn("每日固定规则选1只", component_source)
        self.assertIn("市场因子对照规则", component_source)
        self.assertIn("冻结候选 v2 规则", component_source)
        self.assertIn("v2 开盘买入候选线", component_source)
        self.assertIn("冻结候选 v2", component_source)
        self.assertIn("同池随机基线", component_source)
        self.assertIn("前三名等权组合", component_source)
        self.assertIn("10/200日金叉过滤", component_source)
        self.assertIn("低换手上升趋势", component_source)
        self.assertIn("等权市场基准", component_source)
        self.assertIn("中证500", component_source)
        self.assertIn("中证1000", component_source)
        self.assertIn("指数序列未纳入本次主板样本库，不展示为0。", component_source)
        self.assertIn("每日1万元在前三名等权", component_source)
        self.assertIn("纸面跟踪记录（正式策略与对照组）", component_source)
        self.assertIn("搜索股票、代码、策略、日期", component_source)
        self.assertIn("comparePaperTrackingSignalEntryRows", component_source)
        self.assertIn('defaultSortOrder: "descend"', component_source)
        self.assertIn('sortDirections: ["descend", "ascend"]', component_source)
        self.assertIn("记录分组", component_source)
        self.assertIn("入场状态", component_source)
        self.assertIn("买入口径", component_source)
        self.assertIn("机械5日已退出", component_source)
        self.assertIn("机械10日已退出", component_source)
        self.assertIn("等待10日窗口", component_source)
        self.assertIn("最新10日退出", component_source)
        self.assertIn("paperTrackingTrackExitDay(paperTrackingMechanical10dExitTrack(latestMechanical10d), latestMechanical10d)", component_source)
        self.assertIn("paperTrackingTrackReturn(paperTrackingMechanical10dExitTrack(latestMechanical10d), latestMechanical10d)", component_source)
        self.assertNotIn("latestMechanical10d ? paperTrackingExitDay(latestMechanical10d)", component_source)
        self.assertIn("止盈止损已退出", component_source)
        self.assertIn("等待退出结果", component_source)
        self.assertIn("没有符合当前筛选条件的纸面跟踪记录。", component_source)
        self.assertIn("后验验证完成前仅作为探索结果展示", component_source)
        self.assertIn("sourceCredibilityLabel", component_source)
        self.assertIn("sourceCredibilityColor", component_source)
        self.assertIn("credibility_status", component_source)
        self.assertIn("校验：", component_source)
        self.assertIn("主基准：", component_source)
        self.assertIn("沪深300", component_source)
        self.assertIn("超额收益", component_source)
        self.assertIn("pending_benchmark_data", component_source)
        self.assertIn("待基准", component_source)
        self.assertIn("前向K线", component_source)
        self.assertIn("重跑接口返回 404", component_source)
        self.assertIn("shortpick-feedback-summary", component_source)
        self.assertIn("shortpick-feedback-table", component_source)
        self.assertIn("model_groups", component_source)
        self.assertIn("modelFeedbackDisplayName", component_source)
        self.assertIn("channelDisplayLabel", component_source)
        self.assertIn("feedbackGroupDisplayLabel", component_source)
        self.assertIn("shortpick-benchmark-select", component_source)
        self.assertIn("shortpick-validation-card", component_source)
        self.assertIn('label: "历史回放"', component_source)
        self.assertIn('label: "最新模拟交易"', component_source)
        self.assertIn("title=\"最新模拟交易\"", component_source)
        self.assertIn("它会持续展示到下一次分析生成新的模拟交易为止", component_source)
        self.assertIn("不是按自然日“今天”临时清空或重算", component_source)
        self.assertIn("顶部必须优先展示两个冻结策略指标", component_source)
        self.assertIn("冻结策略 v1", component_source)
        self.assertIn("等待最新分析批次写入", component_source)
        self.assertIn("latestFrozenPaperTrackingChoices", component_source)
        self.assertIn('tracking_group === "frozen_strategy"', component_source)
        self.assertIn('tracking_group === "frozen_strategy_v2"', component_source)
        self.assertIn("latestPaperTrackingSignalDate", component_source)
        self.assertIn("const visibleWorkspaceTab = latestRun || activeWorkspaceTab !== \"today\"", component_source)
        self.assertIn("activeKey={visibleWorkspaceTab}", component_source)
        self.assertIn("loadMarketStudy", component_source)
        self.assertIn("历史回放主体不依赖这项重计算", component_source)
        self.assertIn("候选明细加载中", component_source)
        self.assertIn("来源清单加载中", component_source)
        self.assertIn("全局统计加载中", component_source)
        self.assertIn("严格来源", component_source)
        self.assertIn("可交易验证", component_source)
        self.assertIn("选股模式双口径对照", component_source)
        self.assertIn("逐只候选统计，用来观察选股池平均质量", component_source)
        self.assertIn("长样本5万元滚动资金曲线超额", component_source)
        self.assertIn("短窗口候选统计", component_source)
        self.assertIn("组合资金曲线", component_source)
        self.assertIn('activeWorkspaceTab === "replay"', component_source)
        self.assertIn("void loadReplay(undefined, { includeMarketStudy: true })", component_source)
        self.assertIn("历史分析结论", component_source)
        self.assertIn("可执行性漏斗", component_source)
        self.assertIn("入场假设矩阵", component_source)
        self.assertIn("14点同日口径只按日线代理展示", component_source)
        self.assertIn("稳定性、置信与归因", component_source)
        self.assertIn("长窗口策略样本", component_source)
        self.assertIn("行情切片覆盖", component_source)
        self.assertIn("确定性策略族切片，不替代 LLM 短窗口 replay", component_source)
        self.assertIn("组合置信区间", component_source)
        self.assertIn("组合时间稳定性", component_source)
        self.assertIn("组合收益归因", component_source)
        self.assertIn("股票/行业归因待全量逐笔 artifact", component_source)
        self.assertIn("非 LLM 历史组合期望", component_source)
        self.assertIn("冻结策略位置", component_source)
        self.assertIn("entryPriceSourceLabel", component_source)
        self.assertIn("marketRegimeDisplayLabel", component_source)
        self.assertIn("行情大类", component_source)
        self.assertIn("月度组合样本", component_source)
        self.assertIn("trade_regime_evidence", component_source)
        self.assertIn("交易级切片", component_source)
        self.assertIn("交易样本", component_source)
        self.assertIn("市场阶段", component_source)
        self.assertIn("行业/题材稳定性", component_source)
        self.assertIn("行业归因口径", component_source)
        self.assertIn("去最佳行业后", component_source)
        self.assertIn("下沿未过晋级线", component_source)
        self.assertIn("前向对齐", component_source)
        self.assertIn("页面不会临时推导研究结论", component_source)
        self.assertIn("shortpick-replay-decision-grid", component_source)
        self.assertIn("策略收口接口当前没有可展示数据", component_source)
        self.assertIn('label: "纸面跟踪"', component_source)
        self.assertIn("PaperTrackingTab", component_source)
        self.assertNotIn('label: "今日批次"', component_source)
        self.assertNotIn("下轮股票选择", component_source)
        self.assertNotIn("当前股票选择", component_source)
        self.assertIn("getShortpickPaperTracking", api_source)
        self.assertIn("/shortpick-lab/paper-tracking", api_source)
        self.assertIn("历史回放核心读数", component_source)
        self.assertIn("无上下文直接查询能否短投选股", component_source)
        self.assertIn("1 / 3 / 5 / 10 / 20 日", component_source)
        self.assertIn("模型与对照组比较", component_source)
        self.assertIn("封闭数据包与来源清单", component_source)
        self.assertIn("泄漏审计", component_source)
        self.assertIn("random_same_market_cap_bucket", component_source)
        self.assertIn("momentum_volume_baseline", component_source)
        self.assertIn("去最佳单票", component_source)
        self.assertIn("getShortpickReplayRuns", api_source)
        self.assertIn("/shortpick-lab/replay-runs", api_source)
        self.assertNotIn("<Segmented", component_source)
        self.assertIn('align: "center"', component_source)
        self.assertIn("/shortpick-lab/runs", api_source)
        self.assertIn("/shortpick-lab/candidates", api_source)
        self.assertNotIn("addWatchlist", component_source)
        self.assertNotIn("getStockDashboard", component_source)

    def test_local_preview_does_not_fallback_to_vite_origin_for_api(self) -> None:
        frontend_root = Path(__file__).resolve().parents[1] / "frontend" / "src"
        core_source = (frontend_root / "api" / "core.ts").read_text(encoding="utf-8")

        self.assertIn("function isLocalPreviewOrigin()", core_source)
        self.assertIn("window.location.port !== \"8000\"", core_source)
        self.assertIn("isLocalPreviewOrigin() || mountedDeploymentBase ? [] : [inferOriginBase()]", core_source)
        self.assertIn("!inferLocalBackendBase() && !mountedDeploymentBase && !basesToUse.includes(\"\")", core_source)

    def test_canonical_mounted_route_does_not_probe_root_api_fallbacks(self) -> None:
        frontend_root = Path(__file__).resolve().parents[1] / "frontend" / "src"
        core_source = (frontend_root / "api" / "core.ts").read_text(encoding="utf-8")
        dashboard_api_source = (frontend_root / "api" / "dashboard.ts").read_text(encoding="utf-8")

        self.assertIn("function isSameOriginMountedBase(base: string): boolean", core_source)
        self.assertIn("function hasMountedDeploymentBase(", core_source)
        self.assertIn("const mountedDeploymentBase = hasMountedDeploymentBase(mountedBase, locationBase);", core_source)
        self.assertIn("return !isLocalPreviewOrigin()", core_source)
        self.assertIn("isLocalPreviewOrigin() || mountedDeploymentBase ? [] : [inferOriginBase()]", core_source)
        self.assertIn("mountedDeploymentBase ? [] : [inferSiblingPortBackendBase()]", core_source)
        self.assertIn("!mountedDeploymentBase && !basesToUse.includes(\"\")", core_source)
        self.assertIn("} else if (isSameOriginMountedBase(base)) {", core_source)
        self.assertIn("urls.push(`${base}/api${normalizedPath}`);", core_source)
        self.assertIn("operationsDashboardRequestBehavior", dashboard_api_source)
        self.assertIn("'/stocks/' + encodeURIComponent(symbol) + '/dashboard',", dashboard_api_source)

    def test_workbench_route_defaults_to_shortpick_paper_tracking(self) -> None:
        frontend_root = Path(__file__).resolve().parents[1] / "frontend" / "src"
        app_source = (frontend_root / "App.tsx").read_text(encoding="utf-8")
        shortpick_source = (frontend_root / "components" / "ShortpickLabView.tsx").read_text(encoding="utf-8")
        labels_source = (frontend_root / "components" / "shortpickLabLabels.ts").read_text(encoding="utf-8")
        route_source = (frontend_root / "utils" / "route.ts").read_text(encoding="utf-8")

        self.assertIn('const DEFAULT_VIEW: ViewMode = "shortpick";', app_source)
        self.assertIn('return rawView && VIEW_MODES.has(rawView as ViewMode) ? (rawView as ViewMode) : DEFAULT_VIEW;', app_source)
        self.assertIn('writeWorkbenchRoute({', app_source)
        self.assertIn('view,', app_source)
        self.assertIn('symbol: selectedSymbol,', app_source)
        self.assertIn('stockTab: view === "stock" ? stockActiveTab : null,', app_source)
        self.assertIn('window.addEventListener("popstate", handlePopState);', app_source)
        self.assertIn('writeWorkbenchRoute({ view: "shortpick", shortpickTab: visibleWorkspaceTab }, "replace");', shortpick_source)
        self.assertIn('writeWorkbenchRoute({ view: "shortpick", shortpickTab: key }, "push");', shortpick_source)
        self.assertIn('function loadWorkspaceTab(tab: ShortpickWorkspaceTab): void {', shortpick_source)
        self.assertIn('if (tab === "paper-tracking")', shortpick_source)
        self.assertIn('void loadPaperTracking();', shortpick_source)
        self.assertIn('loadWorkspaceTab(activeWorkspaceTab);', shortpick_source)
        self.assertNotIn('void loadLab();\n    void loadPaperTracking();\n    void loadValidationQueue(1, DEFAULT_VALIDATION_PAGE_SIZE);\n    void loadFeedback();', shortpick_source)
        self.assertIn('if (viewRef.current !== "shortpick")', app_source)
        self.assertIn("getShortpickPaperTrackingSummary", app_source)
        self.assertNotIn("void api.getShortpickPaperTracking()", app_source)
        self.assertIn("/shortpick-lab/paper-tracking/summary", (frontend_root / "api" / "shortpick.ts").read_text(encoding="utf-8"))
        self.assertIn(': "paper-tracking";', labels_source)
        self.assertIn('export function writeWorkbenchRoute(', route_source)
        self.assertIn('window.history[mode === "push" ? "pushState" : "replaceState"]', route_source)


if __name__ == "__main__":
    unittest.main()
