import unittest
from pathlib import Path


class FrontendMobileStaticTests(unittest.TestCase):
    def test_mobile_shell_uses_app_tabs_and_no_operations_wide_table(self) -> None:
        frontend_root = Path(__file__).resolve().parents[1] / "frontend" / "src"
        app_source = (frontend_root / "App.tsx").read_text(encoding="utf-8")
        main_source = (frontend_root / "main.tsx").read_text(encoding="utf-8")
        shell_source = (frontend_root / "components" / "mobile" / "MobileAppShell.tsx").read_text(encoding="utf-8")
        home_source = (frontend_root / "components" / "mobile" / "MobileHome.tsx").read_text(encoding="utf-8")
        stock_row_source = (frontend_root / "components" / "mobile" / "MobileStockRow.tsx").read_text(encoding="utf-8")
        operations_source = (frontend_root / "components" / "mobile" / "MobileOperations.tsx").read_text(encoding="utf-8")
        manual_order_source = (frontend_root / "components" / "mobile" / "MobileManualOrderModal.tsx").read_text(encoding="utf-8")
        settings_source = (frontend_root / "components" / "mobile" / "MobileSettings.tsx").read_text(encoding="utf-8")
        model_selection_source = (frontend_root / "components" / "mobile" / "modelSelection.ts").read_text(encoding="utf-8")
        stock_detail_source = (frontend_root / "components" / "mobile" / "MobileStockDetail.tsx").read_text(encoding="utf-8")
        price_line_source = (frontend_root / "components" / "mobile" / "MobilePriceLineChart.tsx").read_text(encoding="utf-8")
        mini_trend_source = (frontend_root / "components" / "mobile" / "MobileMiniTrendChart.tsx").read_text(encoding="utf-8")
        mobile_style_source = (frontend_root / "mobile.css").read_text(encoding="utf-8")
        mobile_style_source += "\n".join(
            path.read_text(encoding="utf-8")
            for path in sorted((frontend_root / "styles" / "mobile").glob("*.css"))
        )

        self.assertIn('import "./mobile.css";', main_source)
        self.assertIn("if (isMobile) {", app_source)
        self.assertIn("<MobileAppShell", app_source)
        self.assertIn('"首页"', shell_source)
        self.assertIn('"单票"', shell_source)
        self.assertIn('"复盘"', shell_source)
        self.assertIn('"试验"', shell_source)
        self.assertIn('"设置"', shell_source)
        self.assertNotIn('"自选"', shell_source)
        self.assertIn("ExperimentOutlined", shell_source)
        self.assertIn("<ShortpickLabView canTrigger={props.isRootUser}", shell_source)
        self.assertIn('tab === "shortpick"', app_source)
        self.assertIn('tab === "operations" && !props.operations && !props.simulation && !props.operationsLoading', shell_source)
        self.assertNotIn("TrackHoldingsTable", operations_source)
        self.assertNotIn("SimulationTrackCard", operations_source)
        self.assertNotIn("mobile-action-dock", operations_source)
        self.assertIn("查看历史", operations_source)
        self.assertIn("mobile-history-overlay", operations_source)
        self.assertIn("isMeaningfulHistoryEvent", operations_source)
        self.assertIn('actionSummary === "持有"', operations_source)
        self.assertIn("buildStockRecords", operations_source)
        self.assertIn("recent_orders", operations_source)
        self.assertIn('event.event_type !== "order_filled"', operations_source)
        self.assertIn("onOpenManualOrder", operations_source)
        self.assertIn("MobileManualOrderModal", app_source)
        self.assertIn("mobile-manual-order-dialog", manual_order_source)
        self.assertIn("外观主题", settings_source)
        self.assertIn("本机 Codex GPT", settings_source)
        self.assertIn('setPanel("model")', settings_source)
        self.assertIn("props.onSelectAnalysisModel(keyId)", settings_source)
        self.assertIn("Switch size=\"small\"", settings_source)
        self.assertIn("onClick ? <RightOutlined /> : null", settings_source)
        self.assertNotIn("规范路由", settings_source)
        self.assertIn("analysisModelPreferenceKey", model_selection_source)
        self.assertIn("api.setDefaultModelApiKey(keyId)", model_selection_source)
        self.assertIn("selectMobileAnalysisModel", app_source)
        self.assertIn(".mobile-bottom-nav", mobile_style_source)
        self.assertIn(".mobile-settings-option", mobile_style_source)
        self.assertIn(".mobile-app-shell", mobile_style_source)
        self.assertIn("--mobile-color-action", mobile_style_source)
        self.assertIn("添加自选", home_source)
        self.assertIn("提问助手", home_source)
        self.assertIn("关注股票", home_source)
        self.assertIn("刷新时间", home_source)
        self.assertIn("setStockPanel?.(\"question\")", home_source)
        self.assertIn("mobile-section-plain", home_source)
        self.assertIn("mobile-refresh-status-wrap", home_source)
        self.assertNotIn("今日候选", home_source)
        self.assertNotIn("查看单票", home_source)
        self.assertIn("mobile-stock-row-meta", stock_row_source)
        self.assertIn("mobile-stock-row-layout", stock_row_source)
        self.assertIn("mobile-stock-name-line", stock_row_source)
        self.assertIn("mobile-stock-swipe", stock_row_source)
        self.assertIn("mobile-stock-remove-action", stock_row_source)
        self.assertIn("onRequestRemoveWatchlist", home_source)
        self.assertIn('row.source_kind !== "candidate_only"', home_source)
        self.assertIn("onRequestRemoveWatchlist={setPendingRemoval}", app_source)
        self.assertIn("MobilePriceLineChart", stock_detail_source)
        self.assertIn("today_price_chart", stock_detail_source)
        self.assertIn("今日价格轨迹", stock_detail_source)
        self.assertIn("mobile-stock-stat-strip", stock_detail_source)
        self.assertIn("mobile-stock-insight-list", stock_detail_source)
        self.assertIn("mobile-event-analysis-card", stock_detail_source)
        self.assertNotIn("KlinePanel", stock_detail_source)
        self.assertNotIn("claimGateAlertType", stock_detail_source)
        self.assertIn("slice(-60)", price_line_source)
        self.assertIn("toLocaleTimeString", price_line_source)
        self.assertIn("--mobile-color-accent", price_line_source)
        self.assertIn("--mobile-color-positive", mobile_style_source)
        self.assertIn("--mobile-radius-panel", mobile_style_source)
        self.assertIn("price_chart", mini_trend_source)
        self.assertNotIn("last / (1 + return20d)", mini_trend_source)
        self.assertNotIn("mobile-sparkline", mobile_style_source)
        self.assertIn(".mobile-stock-swipe-open .mobile-stock-row", mobile_style_source)
        self.assertIn("--mobile-nav-count", mobile_style_source)
        self.assertIn(".mobile-page-shortpick", mobile_style_source)
        self.assertIn(".mobile-event-analysis-card.mobile-stock-analysis-card", mobile_style_source)
